"""Making thumbnail_url nullable

Revision ID: 4d37d56ab659
Revises: 01318ab48f06
Create Date: 2023-04-06 13:16:21.251883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d37d56ab659'
down_revision = '01318ab48f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_url',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_url',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
